package com.fphoenixcorneae.grouter.constant

object Constant {
    const val KSP_ARGUMENT_KEY_MODULE_NAME = "gRouterModuleName"
    const val KSP_ARGUMENT_KEY_DEFAULT_SCHEME = "gRouterDefaultScheme"
    const val KSP_ARGUMENT_KEY_DEFAULT_HOST = "gRouterDefaultHost"
    const val KSP_ARGUMENT_EXCEPTION_MESSAGE =
        """
            GRouter Processor Can not find ksp argument 'gRouterModuleName', 'gRouterDefaultScheme' or 'gRouterDefaultHost', check if has add the code like this in module's build.gradle.kts:
                ksp {
                    arg("gRouterModuleName", project.name)
                    arg("gRouterDefaultScheme", "your scheme")
                    arg("gRouterDefaultHost", "your host")
                }
        """

    const val ROUTER_DOC = "Automatically generated by GRouter."
    const val ROUTER_METHOD_NAME = "register"
    const val ROUTER_GENERATE_PACKAGE_NAME = "com.fphoenixcorneae.grouter.generate"
    const val ROUTER_GENERATE_CLASS_NAME_PREFIX = "GRouter_"
    const val ROUTER_PACKAGE_NAME = "com.fphoenixcorneae.grouter"
    const val ROUTER_NAME = "GRouter"

    const val CHECK_OBJECT_TYPE_EXCEPTION_MESSAGE =
        "nonsupport route type [%s], only support activity or fragment"
    const val STATEMENT_PARAM_FORMAT = "GRouter.register(%T(%L, %T::class, %L))"

    const val ROUTER_REGISTER_METHOD_NAME = "registerRoutes"
    const val ROUTER_REGISTER_PACKAGE_NAME = "com.fphoenixcorneae.grouter.register"
    const val ROUTER_REGISTER_CLASS_SIMPLE_NAME = "RouteRegister"
    const val ROUTER_REGISTER_CLASS_FULL_NAME = "$ROUTER_REGISTER_PACKAGE_NAME.RouteRegister"
    const val ROUTER_REGISTER_INTERFACE_SIMPLE_NAME = "IRouteRegisterer"
    const val ROUTER_REGISTER_CLASS_CONTENT =
        """
package com.fphoenixcorneae.grouter.register

/**
 * $ROUTER_DOC
 */
class RouteRegister : IRouteRegister {
    override fun registerRoutes() {
    }
}
        """
}