package com.fphoenixcorneae.grouter.ksp

internal object Constant {
    const val KSP_ARGUMENT_KEY_MODULE_NAME = "gRouterModuleName"
    const val KSP_ARGUMENT_KEY_DEFAULT_SCHEME = "gRouterDefaultScheme"
    const val KSP_ARGUMENT_KEY_DEFAULT_HOST = "gRouterDefaultHost"
    const val KSP_ARGUMENT_EXCEPTION_MESSAGE =
        """
            GRouter Processor Can not find ksp argument 'gRouterModuleName', 'gRouterDefaultScheme' or 'gRouterDefaultHost', check if has add the code like this in module's build.gradle.kts:
                ksp {
                    arg("gRouterModuleName", project.name)
                    arg("gRouterDefaultScheme", "your scheme")
                    arg("gRouterDefaultHost", "your host")
                }
        """

    const val ROUTER_METHOD_NAME = "register"
    const val ROUTER_METHOD_DOC = "Automatically generated by Router."
    const val ROUTER_GENERATE_CLASS_NAME_PREFIX = "GRouteGenerate_"
    const val ROUTER_GENERATE_PACKAGE_NAME = "com.fphoenixcorneae.grouter.generate"
    const val ROUTER_PACKAGE_NAME = "com.fphoenixcorneae.grouter"
    const val ROUTER_NAME = "GRouter"

    const val CHECK_OBJECT_TYPE_EXCEPTION_MESSAGE = "nonsupport route type [%s], only support activity or fragment"
    const val STATEMENT_PARAM_FORMAT = "GRouter.register(%T(%L, %T::class, %L))"
}