package com.fphoenixcorneae.grouter.plugin

internal object Constant {
    const val ROUTER_METHOD_DOC = "Automatically generated by Router."
    const val ROUTER_METHOD_NAME = "register"
    const val ROUTER_REGISTER_METHOD_NAME = "registerRoutes"
    const val ROUTER_REGISTER_CLASS_NAME = "com.fphoenixcorneae.grouter.register.RouteRegister"
    const val ROUTER_REGISTER_CLASS_CONTENT =
        """
            package com.fphoenixcorneae.grouter.register
            
            /**
             * $ROUTER_METHOD_DOC
             */
            class RouteRegister : IRouteRegister {
                override fun registerRoutes() {
                }
            }
        """


    const val ROUTER_GENERATE_CLASS_NAME_PREFIX = "GRouteGenerate_"
    const val ROUTER_GENERATE_PACKAGE_NAME = "com.fphoenixcorneae.grouter.generate"
}