{
  "formatVersion": "1.1",
  "component": {
    "group": "GRouter",
    "module": "grouter-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "grouter-plugin-unspecified.jar",
          "url": "grouter-plugin-unspecified.jar",
          "size": 17771,
          "sha512": "e1f331f6fb4486fa2f00573999a5d8287f0aa7fc342dce6c18c3c4bc89a1fde5ec2e3ea928b9bfef6b188638b156e67d58c62203f83f335f6d631e562bdc8f6c",
          "sha256": "c143bb90d30a2103927de7a311b59b24f5e8921d22cad447d8827efd8e69ee8b",
          "sha1": "f4bb98f14700210ac6ed1ce51cb1e28793818efc",
          "md5": "41a8b516be0e97e8aca310c4fa1d1db4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "grouter-plugin-unspecified.jar",
          "url": "grouter-plugin-unspecified.jar",
          "size": 17771,
          "sha512": "e1f331f6fb4486fa2f00573999a5d8287f0aa7fc342dce6c18c3c4bc89a1fde5ec2e3ea928b9bfef6b188638b156e67d58c62203f83f335f6d631e562bdc8f6c",
          "sha256": "c143bb90d30a2103927de7a311b59b24f5e8921d22cad447d8827efd8e69ee8b",
          "sha1": "f4bb98f14700210ac6ed1ce51cb1e28793818efc",
          "md5": "41a8b516be0e97e8aca310c4fa1d1db4"
        }
      ]
    }
  ]
}
